# Generated by Django 3.2.8 on 2022-06-09 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.ManyToManyField(related_name='students', to='users.Language'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='users.language'),
        ),
    ]
