# Generated by Django 3.2.8 on 2022-06-09 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220609_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='language_description',
            field=models.TextField(default='Une langue au Cameroun'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='language_images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
